# .pages.yml — Pages CMS config for this site (Astro content collections)

media:
  name: images
  label: Images
  input: src/images
  output: src/images
  path: "" # start at src/images
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  # ---------------------
  # BLOG POSTS
  # ---------------------
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    filename: "{primary}.md"
    view:
      primary: title
      fields: [title, pubDate, team]
      sort: [pubDate]
      default: { sort: pubDate, order: desc }
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDate
        label: Publication Date
        type: date
      - name: team
        label: Author
        type: string
      - name: description
        label: Description
        type: text
      - name: image
        label: Cover Image
        type: object
        fields:
          - name: url
            label: Image
            type: image
            options:
              media: images
              path: blog
          - name: alt
            label: Alt text
            type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text

  # ---------------------
  # PROJECTS
  # ---------------------
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    filename: "{primary}.md"
    view:
      primary: title
      fields: [title, status, year]
      sort: [pubDate]
      default: { sort: pubDate, order: desc }
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDate
        label: Publication Date
        type: date
      - name: client
        label: Client
        type: string
      - name: location
        label: Location
        type: string
      - name: year
        label: Year
        type: string
      - name: status
        label: Status
        type: string
        options: [concept, in-progress, built]
      - name: area
        label: Area
        type: string
      - name: cover
        label: Cover Image
        type: object
        fields:
          - name: url
            label: Image
            type: image
            options:
              media: images
              path: projects
          - name: alt
            label: Alt text
            type: string
      - name: gallery
        label: Gallery
        type: object
        list: true
        fields:
          - name: url
            label: Image
            type: image
            options:
              media: images
              path: projects
          - name: alt
            label: Alt text
            type: string
      - name: body
        label: Body
        type: rich-text

  # ---------------------
  # TEAM
  # ---------------------
  - name: team
    label: Team
    type: collection
    path: src/content/team
    filename: "{primary}.md"
    view:
      primary: name
      fields: [name, role]
      sort: [name]
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: role
        label: Role
        type: string
      - name: bio
        label: Bio
        type: text
      - name: image
        label: Profile Image
        type: object
        fields:
          - name: url
            label: Image
            type: image
            options:
              media: images
              path: team
          - name: alt
            label: Alt text
            type: string
      - name: socials
        label: Socials
        type: object
        fields:
          - { name: twitter,  label: X/Twitter URL, type: string }
          - { name: website,  label: Website URL,  type: string }
          - { name: linkedin, label: LinkedIn URL, type: string }
          - { name: email,    label: Email,        type: string }
      - name: body
        label: Body
        type: rich-text

  # ---------------------
  # SERVICES
  # ---------------------
  - name: services
    label: Services
    type: collection
    path: src/content/services
    filename: "{primary}.md"
    view:
      primary: title
      fields: [title]
      sort: [title]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: image
        label: Image
        type: object
        fields:
          - name: url
            label: Image
            type: image
            options:
              media: images
              path: services
          - name: alt
            label: Alt text
            type: string
      - name: body
        label: Body
        type: rich-text

  # ---------------------
  # LEGAL PAGES
  # ---------------------
  - name: legal
    label: Legal
    type: collection
    path: src/content/legal
    filename: "{primary}.md"
    view:
      primary: page
      fields: [page, pubDate]
      sort: [page]
    fields:
      - name: page
        label: Page
        type: string
        required: true
      - name: pubDate
        label: Publication Date
        type: date
      - name: body
        label: Body
        type: rich-text
